var questionsJS = [
	"Es javascript un lenguaje tipado?",
	"Es javascript un lenguaje orientado a objetos o orientado a functional?",
	"Es javascript un lenguaje orientado a eventos?",
	"Es javascript un lenguaje orientado a prototipos?",
	"Todos los objetos tienen prototipos?",
	"Cual es el origen de Javascript? (Scheme y Java)",
	"Por que hay 4 diferentes versiones de Javascript? ",
	"Que es una Clase? dispone javascript de clases nativas? ",
	"Es javascript un lenguaje single thread o multi thread?",
	"Para que sirven los web workers?",
	"Que son los namespaces?",
	"Que significa AMD?",
	"Que es Semver?",
	"Defina MVC",
	"Defina 3 patrones de diseño",
	"Que antipatrones de diseño existen?",
	"Cuales son los 3 pasos en que se define una variable?",
	"Que es la persistencia en una variable?",
	"Que es estar suscripto a una variable?",
	"Que es un Closure?",
	"Cuantas formas hay de crearle propiedades a un objeto?",
	"Que es la sobrecarga de funciones/métodos?",
	"Que es el Debounce?",
	"Para que se utiliza comunmente la variable Self?",
	"Que diferencia hay entre hashear una URL y hacer un QueryString?",
	"Para que sirve el método arguments.length dentro de una función?",
	"Para que se usa hasOwnProperty?",
	"Que son los memory leaks?",
	"Que es el DRY code?",
	"Que son las funciones puras y las inpuras?",
	"A que se le conoce como whitelistear?",
	"Que diferencias hay entre GET y POST? porque IE puede traer problemas si se utiliza get con muchos parametros?",
	"Como se copia un array y para que es necesario copiar un array?",
	"Tienen algo que ver el patrón de diseño PUB/SUB con eventBus?",
	"Para que se usa el content-type y el datatype en los forms?",
	"Que es la inmutabilidad? Solo puede solucionarse con ES6?",
	"Que es el var hoisting y que es el function hoisting?",
	"Que significan if(!x) y if(!!x)? defina algún caso de uso. Que tiene que ver con type coersion?",
	"Que es el Stack y el Queued y cual corresponde con FIFO y cual con LIFO?",
	"Se puede utilizar x === “object” para testear si x es un objeto?",
	"Explique la diferencia entre RETURN FALSE, PREVENTDEFAULT Y STOPPROPAGATION",
	"Que diferencia hay entre $(document).ready y $(window).load",
	"Para que se utiliza el método jQuery.noConflict()",
	"Para que sirve el método prototype?",
	"Que son las propiedades y los métodos públicos y privados y como se crea cada uno?",
	"Que es un operador ternario?",
	"Cual es la diferencia entre == y ===, que es la Type coercion?",
	"Por que si comparamos false == 0 nos da true?",
	"Cual es la diferencia for y while? ejemplifique.",
	"Cual es la diferencia entre for y foreach? en que caso conviene usar cada uno?",
	"Cual es la diferencia entre TDD y BDD?",
	"Para que se parsea un JSON ej. JSON.parse()?",
	"Que es JSONP y como se usa y a que se le llama comunmente CORS?",
	"Como saber si tengo acceso a CORS en un dominio externo, donde buscarlo en el navegador?",
	"Que hace esto? que problema soluciona con distintos navegadores? $('li').click(function (e) { var e = window.event || e; });",
	"Para que se usa 'use strict'?",
	"Defina Herencia, Encapsulamiento, Abstracción(función anónima) y Polimorfismo",
	"Que diferencia hay entre $() y find() en Jquery?",
	"Hay alguna diferencia entre $('#mydiv').find('.adiv') y $('.adiv', '#mydiv')?",
	"Que diferencia hay entre Null y Undefined?",
	"Que hace el método .split() y .join() y como se usan?",
	"que significa esta nomenclatura en Jquery $j('li','#cmeSearchFilterResults')?",
	"Que es el Event Bubbling?",
	"Cual es la diferencia entre localstorage, sessionstorage y cookie? ",
	"Que diferencia hay entre bind y call/apply",
	"Para que sirve el método off() en Jquery?",
	"Como ordernar valores de un objeto a una tabla (sort())?",
	"Para que se utilizan objetos literales (function(){...})() en Plugins de JQUERY (function($){})(jQuery); ademas de para crear plugins?",
	"Como crear un plugin en Jquery?",
	"Para que se utiliza el objeto $.Deferred()?",
	"Como desabilitar spellcheck en un input?",
	"Que es el DOM y el BOM?",
	"Que soluciona 'cache : false' en IE?",
	"Que son los getters y setters?",
	"Que son getters y setters en JQuery?",
	"Como remover un elemento en JQuery? que diferencia hay entre .remove(), .detach() and empty()?",
	"Explique .bind() vs .live() vs .delegate() vs .on()?",
	"Que significa pasar por valor y pasar por referencia en una function?",
	"Cuales son las 3 formas que hay de definir una función?",
	"Que hace Object.keys()?",
	"Para que se puede utilizar Object.defineProperty()?",
	"Para que se usa seal(), freeze()?",
	"Que es el constructor en un objeto?",
	"Que es el manejo de excepciones?",
	"Para que se utiliza encodeURI y decodeURI?",
	"Que es la programación recursiva?"
];